# Generated by Django 5.1.4 on 2026-05-29 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Лекарство')),
                ('form', models.CharField(choices=[('tablets', 'Таблетки'), ('capsules', 'Капсулы'), ('drops', 'Капли'), ('ointment', 'Мазь'), ('solution', 'Раствор'), ('other', 'Другое')], default='tablets', max_length=20, verbose_name='Форма')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Остаток')),
                ('unit', models.CharField(max_length=30, verbose_name='Единица')),
                ('min_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Мин. остаток')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Лекарство',
                'verbose_name_plural': 'Лекарства',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PatientMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=200, verbose_name='Дозировка')),
                ('duration', models.CharField(max_length=100, verbose_name='Длительность')),
                ('date', models.DateField(verbose_name='Дата назначения')),
                ('notes', models.TextField(blank=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='Врач')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='medicines.medicine', verbose_name='Лекарство')),
            ],
            options={
                'verbose_name': 'Назначение лекарства',
                'verbose_name_plural': 'Назначения лекарств',
                'ordering': ['-date'],
            },
        ),
    ]
