# Generated by Django 5.1.4 on 2026-05-29 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0002_initial'),
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmedicine',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='treatments.treatment', verbose_name='Приём'),
        ),
    ]
