# Generated by Django 5.1.4 on 2026-06-05 08:04

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


def backfill_clinic(apps, schema_editor):
    """Существующим задачам проставить клинику создателя."""
    Task = apps.get_model('tasks', 'Task')
    for t in Task.objects.filter(clinic__isnull=True).select_related('created_by'):
        cid = getattr(t.created_by, 'clinic_id', None)
        if cid:
            Task.objects.filter(pk=t.pk).update(clinic_id=cid)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('users', '0008_user_can_view_all_appointments'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='task',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_clinics', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.clinic', verbose_name='Клиника'),
        ),
        migrations.RunPython(backfill_clinic, noop),
    ]
