# Generated by Django 5.1.4 on 2026-05-29 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Баланс')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Техник',
                'verbose_name_plural': 'Технические специалисты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена договора')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician_agreements', to='services.service')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='technicians.technician')),
            ],
            options={
                'verbose_name': 'Договор с техником',
                'verbose_name_plural': 'Договоры с техниками',
            },
        ),
        migrations.AddField(
            model_name='technician',
            name='services',
            field=models.ManyToManyField(blank=True, through='technicians.TechnicianAgreement', to='services.service', verbose_name='Услуги'),
        ),
        migrations.CreateModel(
            name='TechnicianTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В работе'), ('done', 'Готово')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость работы')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Срок')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tech_tasks', to='services.service')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tech_tasks', to='technicians.technician')),
            ],
            options={
                'verbose_name': 'Задание технику',
                'verbose_name_plural': 'Задания техникам',
                'ordering': ['-created_at'],
            },
        ),
    ]
