# Generated by Django 5.1.4 on 2026-05-29 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technicians', '0001_initial'),
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniciantask',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tech_tasks', to='treatments.treatment'),
        ),
        migrations.AlterUniqueTogether(
            name='technicianagreement',
            unique_together={('technician', 'service')},
        ),
    ]
