# Generated by Django 5.1.4 on 2026-06-22 18:07

import apps.tenancy
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_fix_via_cashier'),
        ('patients', '0011_patientvisit'),
        ('technicians', '0002_initial'),
        ('treatments', '0015_historicaltreatment_public_token_and_more'),
        ('users', '0016_clinic_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techniciantask',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ технику', 'verbose_name_plural': 'Заказы техникам'},
        ),
        migrations.AlterModelManagers(
            name='technician',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_clinics', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='techniciantask',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_clinics', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='technician',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.clinic', verbose_name='Клиника'),
        ),
        migrations.AddField(
            model_name='technician',
            name='default_lead_days',
            field=models.PositiveIntegerField(default=5, verbose_name='Срок изготовления по умолчанию (дней)'),
        ),
        migrations.AddField(
            model_name='technician',
            name='lab_contact',
            field=models.CharField(blank=True, max_length=200, verbose_name='Контакт лаборатории'),
        ),
        migrations.AddField(
            model_name='technician',
            name='lab_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Лаборатория'),
        ),
        migrations.AddField(
            model_name='technician',
            name='specialization',
            field=models.CharField(blank=True, choices=[('ceramic', 'Металлокерамика'), ('zirconia', 'Цирконий'), ('removable', 'Съёмные протезы'), ('implant', 'Импланты'), ('ortho', 'Ортодонтия (каппы, пластинки)'), ('combined', 'Комбинированная'), ('other', 'Другое')], max_length=20, verbose_name='Специализация'),
        ),
        migrations.AddField(
            model_name='techniciantask',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.clinic', verbose_name='Клиника'),
        ),
        migrations.AddField(
            model_name='techniciantask',
            name='cure',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_order_obj', to='treatments.treatmentcure'),
        ),
        migrations.AddField(
            model_name='techniciantask',
            name='doctor_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий врача технику'),
        ),
        migrations.AddField(
            model_name='techniciantask',
            name='expected_ready',
            field=models.DateField(blank=True, null=True, verbose_name='Ожидаемая готовность'),
        ),
        migrations.AddField(
            model_name='techniciantask',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.expense'),
        ),
        migrations.AddField(
            model_name='techniciantask',
            name='installed_at',
            field=models.DateField(blank=True, null=True, verbose_name='Установлено'),
        ),
        migrations.AddField(
            model_name='techniciantask',
            name='material',
            field=models.CharField(blank=True, max_length=120, verbose_name='Материал / тип работы'),
        ),
        migrations.AddField(
            model_name='techniciantask',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено технику'),
        ),
        migrations.AddField(
            model_name='techniciantask',
            name='paid_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='techniciantask',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tech_orders', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='techniciantask',
            name='ready_at',
            field=models.DateField(blank=True, null=True, verbose_name='Готов (факт)'),
        ),
        migrations.AddField(
            model_name='techniciantask',
            name='tooth_number',
            field=models.CharField(blank=True, max_length=120, verbose_name='Зуб'),
        ),
        migrations.AddField(
            model_name='techniciantask',
            name='transferred_at',
            field=models.DateField(blank=True, null=True, verbose_name='Передан в работу'),
        ),
        migrations.AddField(
            model_name='techniciantask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='techniciantask',
            name='vita_color',
            field=models.CharField(blank=True, max_length=20, verbose_name='Цвет (Vita)'),
        ),
        migrations.AddField(
            model_name='techniciantask',
            name='warranty_until',
            field=models.DateField(blank=True, null=True, verbose_name='Гарантия до'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='techniciantask',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Стоимость работы техника'),
        ),
        migrations.AlterField(
            model_name='techniciantask',
            name='status',
            field=models.CharField(choices=[('transferred', 'Передан в работу'), ('in_progress', 'В изготовлении'), ('ready', 'Готов'), ('fitting', 'Примерка'), ('correction', 'Коррекция'), ('installed', 'Установлено'), ('cancelled', 'Отменено')], default='transferred', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='TechnicianOrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('transferred', 'Передан в работу'), ('in_progress', 'В изготовлении'), ('ready', 'Готов'), ('fitting', 'Примерка'), ('correction', 'Коррекция'), ('installed', 'Установлено'), ('cancelled', 'Отменено')], max_length=20)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='technicians.techniciantask')),
            ],
            options={
                'ordering': ['at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianOrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tech_orders/%Y/%m/')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='technicians.techniciantask')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicianWarrantyCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Причина обращения')),
                ('resolved', models.BooleanField(default=False, verbose_name='Решено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.clinic', verbose_name='Клиника')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='patients.patient')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_cases', to='technicians.techniciantask')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_cases', to='technicians.technician')),
            ],
            options={
                'verbose_name': 'Гарантийный случай',
                'verbose_name_plural': 'Гарантийные случаи',
                'ordering': ['-created_at'],
            },
            bases=(apps.tenancy._ClinicSaveMixin, models.Model),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_clinics', django.db.models.manager.Manager()),
            ],
        ),
    ]
