# Generated by Django 5.1.4 on 2026-05-31 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('warehouse', '0002_inventorydocument_inventoryitem_warehousetransfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Код услуги'),
        ),
        migrations.AddField(
            model_name='service',
            name='dms_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена ДМС (сом)'),
        ),
        migrations.CreateModel(
            name='ServiceMaterialNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_norms', to='warehouse.product', verbose_name='Материал')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_norms', to='services.service')),
            ],
            options={
                'verbose_name': 'Норматив расхода',
                'verbose_name_plural': 'Нормативы расхода',
                'unique_together': {('service', 'product')},
            },
        ),
    ]
