# Generated by Django 5.1.4 on 2026-06-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_managers_service_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_lab',
            field=models.BooleanField(default=False, verbose_name='Лабораторная работа'),
        ),
        migrations.AddField(
            model_name='service',
            name='lab_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Срок изготовления (дней)'),
        ),
        migrations.AddField(
            model_name='service',
            name='warranty_months',
            field=models.PositiveIntegerField(default=0, verbose_name='Гарантия (мес.)'),
        ),
    ]
