# Generated by Django 5.1.4 on 2026-08-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_is_lab_service_lab_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price_secondary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена (доп. валюта)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена (осн. валюта)'),
        ),
    ]
