# Generated by Django 5.1.4 on 2026-06-19 14:23

import uuid
from django.db import migrations, models


def gen_tokens(apps, schema_editor):
    """Уникальный токен каждому существующему платежу (callable default даёт всем одинаковый)."""
    Payment = apps.get_model("finance", "Payment")
    for pk in Payment.objects.values_list("pk", flat=True):
        Payment.objects.filter(pk=pk).update(public_token=uuid.uuid4())


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_expense_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='public_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(gen_tokens, migrations.RunPython.noop),
    ]
