# Generated by Django 5.1.4 on 2026-06-21 14:48

from django.db import migrations, models


def backfill_via_cashier(apps, schema_editor):
    """Существующие платежи, принятые администратором/кассиром (не врачом), помечаем кассовыми."""
    Payment = apps.get_model("finance", "Payment")
    Role = apps.get_model("users", "Role")
    admin_role_names = ["superadmin", "admin_main", "admin"]
    # id пользователей, у кого есть админ-роль (основная или доп.)
    from django.db.models import Q
    User = apps.get_model("users", "User")
    admin_ids = set(
        User.objects.filter(
            Q(role__name__in=admin_role_names) | Q(roles__name__in=admin_role_names)
        ).values_list("id", flat=True)
    )
    if admin_ids:
        Payment.objects.filter(received_by_id__in=admin_ids).update(via_cashier=True)


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_payment_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='via_cashier',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Принято в кассе'),
        ),
        migrations.RunPython(backfill_via_cashier, migrations.RunPython.noop),
    ]
