# Generated by Django 5.1.4 on 2026-06-23 16:28

import django.db.models.deletion
from django.db import migrations, models


def backfill_allocations(apps, schema_editor):
    """Существующие income-платежи с привязанным приёмом → одно распределение на этот приём."""
    Payment = apps.get_model("finance", "Payment")
    PaymentAllocation = apps.get_model("finance", "PaymentAllocation")
    for p in Payment.objects.filter(type="income", treatment__isnull=False):
        PaymentAllocation.objects.create(payment_id=p.id, treatment_id=p.treatment_id, amount=p.amount)


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_fix_via_cashier'),
        ('treatments', '0016_treatmentcure_lab_order_treatmentcure_warranty_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.payment')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='treatments.treatment')),
            ],
            options={
                'verbose_name': 'Распределение платежа',
                'verbose_name_plural': 'Распределения платежей',
            },
        ),
        migrations.RunPython(backfill_allocations, migrations.RunPython.noop),
    ]
