# Generated by Django 5.1.4 on 2026-08-06 19:31

import apps.tenancy
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_paymentallocation'),
        ('users', '0022_seed_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('closed', 'Закрыта')], default='open', max_length=10, verbose_name='Статус')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Наличные на начало смены')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closing_cash_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Наличные по факту на закрытии')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_shifts', to='users.branch', verbose_name='Филиал')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.clinic', verbose_name='Клиника')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_cash_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Закрыл')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_cash_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Открыл')),
            ],
            options={
                'verbose_name': 'Кассовая смена',
                'verbose_name_plural': 'Кассовые смены',
                'ordering': ['-opened_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('branch',), name='one_open_cash_shift_per_branch')],
            },
            bases=(apps.tenancy._ClinicSaveMixin, models.Model),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_clinics', django.db.models.manager.Manager()),
            ],
        ),
    ]
