from django.urls import path
from . import views

urlpatterns = [
    path("", views.staff_list, name="staff_list"),
    path("create/", views.staff_create, name="staff_create"),
    path("<int:pk>/edit/", views.staff_edit, name="staff_edit"),
    path("<int:pk>/delete/", views.staff_delete, name="staff_delete"),
    path("<int:pk>/set-password/", views.staff_set_password, name="staff_set_password"),
    path("branches/", views.branch_list, name="branch_list"),
    path("branches/create/", views.branch_create, name="branch_create"),
    path("branches/<int:pk>/edit/", views.branch_edit, name="branch_edit"),
    path("branches/<int:branch_pk>/cabinets/add/", views.cabinet_create, name="cabinet_create"),
    path("cabinets/<int:pk>/delete/", views.cabinet_delete, name="cabinet_delete"),
    path("salary/", views.salary_report, name="salary_report"),
    path("salary/export/", views.salary_export, name="salary_export"),
    path("my-earnings/", views.my_earnings, name="my_earnings"),
    path("salary/<int:pk>/scheme/", views.salary_scheme_edit, name="salary_scheme_edit"),
    path("schedule/", views.schedule_list, name="schedule_list"),
    path("schedule/<int:pk>/edit/", views.schedule_edit, name="schedule_edit"),
    path("superadmin/", views.superadmin_panel, name="superadmin_panel"),
    path("superadmin/seed-dental/", views.seed_dental_view, name="seed_dental"),
    path("set-branch/", views.set_active_branch, name="set_active_branch"),
    path("set-clinic/", views.set_active_clinic, name="set_active_clinic"),
    path("clinic/<int:clinic_id>/overview/", views.clinic_overview, name="clinic_overview"),
    path("clinic/<int:clinic_id>/site-toggle/", views.toggle_clinic_site, name="toggle_clinic_site"),
    path("clinic/<int:clinic_id>/site/", views.clinic_site_edit, name="clinic_site_edit"),
    path("<int:pk>/access/", views.save_user_access, name="save_user_access"),
    path("recycle-bin/", views.recycle_bin, name="recycle_bin"),
    path("recycle-bin/<str:kind>/<int:pk>/restore/", views.recycle_restore, name="recycle_restore"),
    path("recycle-bin/<str:kind>/<int:pk>/purge/", views.recycle_purge, name="recycle_purge"),
]
