# Generated by Django 5.1.4 on 2026-05-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinic/', verbose_name='Логотип')),
                ('name', models.CharField(max_length=200, verbose_name='Название клиники')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Адрес')),
                ('working_hours', models.JSONField(default=dict, help_text='{"mon": ["09:00","18:00"], "tue": ["09:00","18:00"], ...}', verbose_name='Рабочие часы')),
                ('appointment_slot', models.PositiveIntegerField(default=30, verbose_name='Слот записи (мин)')),
                ('currency', models.CharField(default='KGS', max_length=10, verbose_name='Валюта')),
                ('language', models.CharField(default='ru', max_length=5, verbose_name='Язык')),
                ('require_unique_phone', models.BooleanField(default=True, verbose_name='Уникальный телефон')),
                ('telegram_bot_token', models.CharField(blank=True, max_length=200, verbose_name='Telegram Bot Token')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки клиники',
                'verbose_name_plural': 'Настройки клиники',
            },
        ),
    ]
