# Generated by Django 5.1.4 on 2026-05-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('doc_type', models.CharField(choices=[('consent', 'Информированное согласие'), ('contract', 'Договор'), ('prescription', 'Назначение / рецепт'), ('referral', 'Направление'), ('certificate', 'Справка'), ('other', 'Другое')], default='consent', max_length=20, verbose_name='Тип')),
                ('content', models.TextField(help_text='Используйте переменные: {{patient_name}}, {{patient_dob}}, {{doctor_name}}, {{clinic_name}}, {{date}}, {{services}}, {{tooth_numbers}}', verbose_name='Содержимое')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Шаблон документа',
                'verbose_name_plural': 'Шаблоны документов',
                'ordering': ['doc_type', 'name'],
            },
        ),
    ]
