# Generated by Django 5.1.4 on 2026-06-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_clinic', '0002_documenttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsettings',
            name='enabled_modules',
            field=models.JSONField(blank=True, default=list, verbose_name='Доступные модули (тариф)'),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='tariff_plan',
            field=models.CharField(blank=True, default='full', max_length=50, verbose_name='Тарифный план'),
        ),
    ]
