# Generated by Django 5.1.4 on 2026-06-05 04:08

import django.db.models.deletion
from django.db import migrations, models


def attach_existing(apps, schema_editor):
    """Существующую singleton-настройку привязать к первой/совпадающей по имени клинике."""
    ClinicSettings = apps.get_model('settings_clinic', 'ClinicSettings')
    Clinic = apps.get_model('users', 'Clinic')
    cs = ClinicSettings.objects.filter(clinic__isnull=True).order_by('pk').first()
    if cs is None:
        return
    clinic = Clinic.objects.filter(name=cs.name).order_by('pk').first() \
        or Clinic.objects.order_by('pk').first()
    if clinic is not None and not ClinicSettings.objects.filter(clinic=clinic).exists():
        cs.clinic = clinic
        cs.save(update_fields=['clinic'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('settings_clinic', '0004_alter_documenttemplate_managers_and_more'),
        ('users', '0008_user_can_view_all_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsettings',
            name='clinic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='users.clinic', verbose_name='Клиника'),
        ),
        migrations.RunPython(attach_existing, noop),
    ]
