# Generated by Django 5.1.4 on 2026-06-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_clinic', '0005_clinicsettings_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsettings',
            name='wa_remind_day',
            field=models.BooleanField(default=True, verbose_name='Напоминать за день до приёма'),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='wa_remind_debt_days',
            field=models.PositiveIntegerField(default=7, verbose_name='Напоминать должникам каждые N дней (0 — выкл)'),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='wa_remind_hour',
            field=models.BooleanField(default=True, verbose_name='Напоминать за час до приёма'),
        ),
    ]
