# Generated by Django 5.1.4 on 2026-06-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_clinic', '0006_clinicsettings_wa_remind_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsettings',
            name='wa_api_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Green-API URL (необязательно)'),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='wa_enabled',
            field=models.BooleanField(default=True, verbose_name='WhatsApp включён для клиники'),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='wa_id_instance',
            field=models.CharField(blank=True, max_length=50, verbose_name='Green-API ID инстанса'),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='wa_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Номер WhatsApp клиники'),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='wa_token',
            field=models.CharField(blank=True, max_length=120, verbose_name='Green-API токен'),
        ),
    ]
