# Generated by Django 5.1.4 on 2026-06-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_clinic', '0007_clinicsettings_wa_api_url_clinicsettings_wa_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsettings',
            name='visits_journal_staff',
            field=models.BooleanField(default=True, verbose_name='Журнал посещений виден персоналу'),
        ),
    ]
