# Generated by Django 5.1.4 on 2026-06-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_clinic', '0008_clinicsettings_visits_journal_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsettings',
            name='warranty_terms',
            field=models.TextField(blank=True, default='Гарантия действует при соблюдении гигиены полости рта и профилактических осмотрах раз в 6 месяцев. Не распространяется на механические повреждения, травмы и несоблюдение рекомендаций врача.', verbose_name='Условия гарантии (лаб. работы)'),
        ),
    ]
