# Generated by Django 5.1.4 on 2026-07-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_clinic', '0009_clinicsettings_warranty_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsettings',
            name='receipt_format',
            field=models.CharField(choices=[('thermal', '80мм термолента (с QR)'), ('a4', 'A4 (PDF)'), ('both', 'Оба формата (выбор при печати)')], default='thermal', max_length=10, verbose_name='Формат чека'),
        ),
    ]
