# Generated by Django 5.1.4 on 2026-07-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_clinic', '0010_add_receipt_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsettings',
            name='receipt_address',
            field=models.CharField(blank=True, help_text='Если не заполнено — используется адрес клиники выше', max_length=500, verbose_name='Адрес в чеке'),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='receipt_clinic_name',
            field=models.CharField(blank=True, help_text='Если не заполнено — используется название клиники выше', max_length=200, verbose_name='Название клиники в чеке'),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='receipt_inn',
            field=models.CharField(blank=True, max_length=30, verbose_name='ИНН/ИИН'),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='receipt_legal_name',
            field=models.CharField(blank=True, help_text='напр. "ИП Иванов Иван Иванович"', max_length=300, verbose_name='ИП / юр. лицо'),
        ),
    ]
