# Generated by Django 5.1.4 on 2026-07-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_clinic', '0011_clinicsettings_receipt_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsettings',
            name='telegram_bot_username',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя бота (@username)'),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='telegram_enabled',
            field=models.BooleanField(default=True, verbose_name='Telegram включён для клиники'),
        ),
    ]
