# Generated by Django 5.1.4 on 2026-08-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_clinic', '0012_clinicsettings_telegram_bot_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsettings',
            name='currency_secondary',
            field=models.CharField(blank=True, max_length=10, verbose_name='Дополнительная валюта'),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='currency',
            field=models.CharField(default='KGS', max_length=10, verbose_name='Основная валюта'),
        ),
    ]
