# Generated by Django 5.1.4 on 2026-08-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_clinic', '0013_clinicsettings_currency_secondary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsettings',
            name='menu_prefs',
            field=models.JSONField(blank=True, default=dict, verbose_name='Настройка меню клиники'),
        ),
    ]
