# Generated by Django 5.1.4 on 2026-08-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_clinic", "0014_clinicsettings_menu_prefs"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicsettings",
            name="recycle_bin_staff",
            field=models.BooleanField(
                default=False, verbose_name="Корзина видна персоналу"
            ),
        ),
    ]
