# Generated by Django 5.1.4 on 2026-08-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_clinic", "0015_clinicsettings_recycle_bin_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicsettings",
            name="telegram_webhook_secret",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Секрет вебхука Telegram"
            ),
        ),
    ]
