# Generated by Django 5.1.4 on 2026-09-14 22:20

from django.db import migrations, models

# Код страны по валюте клиники: настройки страны в системе нет, а валюта есть
# и у всех заполнена. Так существующие клиники получают верный код сразу, без
# ручной настройки — узбекским номерам это критично, они и ломались.
CURRENCY_TO_CODE = {
    "UZS": "998",
    "KGS": "996",
    "KZT": "7",
    "RUB": "7",
    "TJS": "992",
}


def set_codes_by_currency(apps, schema_editor):
    ClinicSettings = apps.get_model("settings_clinic", "ClinicSettings")
    for cs in ClinicSettings.objects.all():
        code = CURRENCY_TO_CODE.get((cs.currency or "").upper().strip())
        if code and cs.phone_country_code != code:
            cs.phone_country_code = code
            cs.save(update_fields=["phone_country_code"])


def noop(apps, schema_editor):
    """Откат ничего не делает: поле всё равно удаляется обратной миграцией."""


class Migration(migrations.Migration):

    dependencies = [
        ('settings_clinic', '0016_clinicsettings_telegram_webhook_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsettings',
            name='phone_country_code',
            field=models.CharField(default='996', max_length=5, verbose_name='Код страны для номеров'),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='primary_messenger',
            field=models.CharField(choices=[('wa', 'WhatsApp'), ('tg', 'Telegram')], default='wa', max_length=10, verbose_name='Основной мессенджер'),
        ),
        migrations.RunPython(set_codes_by_currency, noop),
    ]
