# Generated by Django 5.1.4 on 2026-09-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_clinic", "0017_clinicsettings_phone_country_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicsettings",
            name="qr_logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="clinic/qr/",
                verbose_name="Логотип для QR",
            ),
        ),
    ]
