# Generated by Django 5.1.4 on 2026-10-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_clinic", "0018_clinicsettings_qr_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documenttemplate",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("consent", "Информированное согласие"),
                    ("contract", "Договор"),
                    ("prescription", "Назначение / рецепт"),
                    ("referral", "Направление"),
                    ("certificate", "Справка"),
                    ("plan_note", "Текст к плану лечения (печать)"),
                    ("other", "Другое"),
                ],
                default="consent",
                max_length=20,
                verbose_name="Тип",
            ),
        ),
    ]
