# Generated by Django 5.1.4 on 2026-10-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_clinic", "0019_plan_note_doc_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicsettings",
            name="salary_discount_shared",
            field=models.BooleanField(
                default=True, verbose_name="Скидка уменьшает зарплату врача"
            ),
        ),
    ]
