# Generated by Django 5.1.4 on 2026-10-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_clinic", "0020_salary_discount_shared"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicsettings",
            name="ai_patient_bot",
            field=models.BooleanField(
                default=False, verbose_name="ИИ-ассистент отвечает пациентам"
            ),
        ),
        migrations.AddField(
            model_name="clinicsettings",
            name="ai_patient_delay_min",
            field=models.PositiveIntegerField(
                default=5, verbose_name="Ассистент отвечает, если админ молчит (мин)"
            ),
        ),
        migrations.AddField(
            model_name="clinicsettings",
            name="ai_patient_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
