# Generated by Django 5.1.4 on 2026-06-02 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_inventorydocument_inventoryitem_warehousetransfer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseentry',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='warehouse.supplier', verbose_name='Поставщик'),
        ),
    ]
