# Generated by Django 5.1.4 on 2026-05-31 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_branch_id_alter_role_id_alter_user_date_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_type', models.CharField(choices=[('fixed', 'Фиксированная ставка'), ('percent_revenue', '% от выручки'), ('percent_paid', '% от оплат (кассовый)'), ('combined', 'Ставка + %')], default='fixed', max_length=20, verbose_name='Схема')),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Фиксированная ставка (сом/мес)')),
                ('percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Процент (%)')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Описание')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_scheme', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Схема зарплаты',
                'verbose_name_plural': 'Схемы зарплат',
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Начало работы')),
                ('end_time', models.TimeField(verbose_name='Конец работы')),
                ('is_working', models.BooleanField(default=True, verbose_name='Рабочий день')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='users.branch', verbose_name='Филиал')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL, verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'График работы',
                'verbose_name_plural': 'Графики работы',
                'ordering': ['doctor', 'day_of_week'],
                'unique_together': {('doctor', 'branch', 'day_of_week')},
            },
        ),
    ]
