# Generated by Django 5.1.4 on 2026-06-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_default_clinic_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='enabled_modules',
            field=models.JSONField(blank=True, default=list, verbose_name='Включённые модули'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='tariff_plan',
            field=models.CharField(default='standard', max_length=20, verbose_name='Тариф'),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users_extra', to='users.role', verbose_name='Доп. роли'),
        ),
    ]
