# Generated by Django 5.1.4 on 2026-06-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_clinic_enabled_modules_clinic_tariff_plan_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='tariff_until',
            field=models.DateField(blank=True, null=True, verbose_name='Тариф оплачен до'),
        ),
    ]
