# Generated by Django 5.1.4 on 2026-06-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_clinic_tariff_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_view_all_appointments',
            field=models.BooleanField(default=True, help_text='Если выключено — врач видит только свои записи', verbose_name='Видит записи всех врачей'),
        ),
    ]
