# Generated by Django 5.1.4 on 2026-06-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_allowed_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('superadmin', 'Суперадмин AKM SOFT'), ('admin_main', 'Директор'), ('admin', 'Администратор'), ('doctor', 'Доктор'), ('nurse', 'Медсестра')], max_length=50, unique=True, verbose_name='Роль'),
        ),
    ]
