# Generated by Django 5.1.4 on 2026-06-06 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_role_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Включает только суперадмин', verbose_name='Публичный сайт включён')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('headline', models.CharField(blank=True, max_length=200, verbose_name='Заголовок (hero)')),
                ('tagline', models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок')),
                ('about', models.TextField(blank=True, verbose_name='О клинике')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адрес')),
                ('hours', models.CharField(blank=True, max_length=200, verbose_name='Часы работы')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Логотип')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Обложка (hero)')),
                ('theme_color', models.CharField(default='#4F46E5', max_length=20, verbose_name='Цвет темы')),
                ('instagram', models.CharField(blank=True, max_length=200)),
                ('whatsapp', models.CharField(blank=True, max_length=50)),
                ('telegram', models.CharField(blank=True, max_length=100)),
                ('show_doctors', models.BooleanField(default=True, verbose_name='Показывать врачей')),
                ('show_services', models.BooleanField(default=True, verbose_name='Показывать услуги')),
                ('show_booking', models.BooleanField(default=True, verbose_name='Онлайн-запись')),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_description', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site', to='users.clinic', verbose_name='Клиника')),
            ],
            options={
                'verbose_name': 'Сайт клиники',
                'verbose_name_plural': 'Сайты клиник',
            },
        ),
    ]
