# Generated by Django 5.1.4 on 2026-06-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_clinicsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта (для карты)'),
        ),
        migrations.AddField(
            model_name='branch',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота (для карты)'),
        ),
    ]
