# Generated by Django 5.1.4 on 2026-06-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_branch_latitude_branch_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='hours',
            field=models.CharField(blank=True, max_length=200, verbose_name='Часы работы'),
        ),
    ]
