# Generated by Django 5.1.4 on 2026-06-11 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_bio_user_experience_years_user_show_on_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=200, verbose_name='Google email')),
                ('refresh_token', models.TextField(verbose_name='Refresh token')),
                ('access_token', models.TextField(blank=True, verbose_name='Access token')),
                ('token_expiry', models.DateTimeField(blank=True, null=True, verbose_name='Срок access token')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gcal_account', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Google Calendar аккаунт',
                'verbose_name_plural': 'Google Calendar аккаунты',
            },
        ),
    ]
