# Generated by Django 5.1.4 on 2026-06-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_googlecalendaraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='timezone',
            field=models.CharField(choices=[('Asia/Bishkek', 'Бишкек (Кыргызстан, UTC+6)'), ('Asia/Almaty', 'Алматы / Астана (Казахстан, UTC+5)'), ('Asia/Tashkent', 'Ташкент (Узбекистан, UTC+5)'), ('Asia/Dushanbe', 'Душанбе (Таджикистан, UTC+5)'), ('Asia/Ashgabat', 'Ашхабад (Туркменистан, UTC+5)'), ('Asia/Yekaterinburg', 'Екатеринбург (Россия, UTC+5)'), ('Asia/Omsk', 'Омск (Россия, UTC+6)'), ('Asia/Novosibirsk', 'Новосибирск (Россия, UTC+7)'), ('Europe/Moscow', 'Москва (Россия, UTC+3)'), ('Europe/Kyiv', 'Киев (Украина, UTC+2)'), ('Europe/Minsk', 'Минск (Беларусь, UTC+3)'), ('Asia/Baku', 'Баку (Азербайджан, UTC+4)'), ('Asia/Yerevan', 'Ереван (Армения, UTC+4)'), ('Asia/Tbilisi', 'Тбилиси (Грузия, UTC+4)'), ('Asia/Dubai', 'Дубай (ОАЭ, UTC+4)'), ('Asia/Istanbul', 'Стамбул (Турция, UTC+3)'), ('UTC', 'UTC (всемирное время)')], default='Asia/Bishkek', help_text='Время записей и расписания показывается в этом поясе на всех устройствах.', max_length=64, verbose_name='Часовой пояс (город/страна)'),
        ),
    ]
