# Generated by Django 5.1.4 on 2026-07-19 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_clinic_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRevert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(max_length=20, verbose_name='Модель')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID записи')),
                ('reverted_to_hid', models.PositiveIntegerField(verbose_name='ID версии, к которой откатили')),
                ('reverted_to_date', models.DateTimeField(verbose_name='Дата версии, к которой откатили')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда откатили')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Откат в аудите',
                'verbose_name_plural': 'Откаты в аудите',
                'ordering': ['-performed_at'],
            },
        ),
    ]
