# Generated by Django 5.1.4 on 2026-07-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auditrevert'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='telegram_master_enabled',
            field=models.BooleanField(default=True, verbose_name='Telegram разрешён клинике'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='wa_master_enabled',
            field=models.BooleanField(default=True, verbose_name='WhatsApp разрешён клинике'),
        ),
    ]
