# Generated by Django 5.1.4 on 2026-07-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_clinic_telegram_master_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='doctor_types',
            field=models.JSONField(blank=True, default=list, help_text='Для фильтра по специализации при записи на приём', verbose_name='Тип врача'),
        ),
    ]
