# Generated by Django 5.1.4 on 2026-07-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_user_doctor_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='color',
            field=models.CharField(blank=True, help_text='Необязательно. Используется для аватара и различения врачей в расписании. Пусто — обычный фиолетовый градиент.', max_length=7, verbose_name='Цвет'),
        ),
    ]
