# Generated by Django 5.1.4 on 2026-07-31 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0020_user_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Код')),
                ('category', models.CharField(choices=[('finance', 'Финансы'), ('patients', 'Пациенты'), ('staff', 'Персонал'), ('reports', 'Отчёты')], max_length=32, verbose_name='Категория')),
                ('label', models.CharField(max_length=255, verbose_name='Название')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='Подсказка')),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Право доступа',
                'verbose_name_plural': 'Права доступа',
                'ordering': ['category', 'sort_order', 'label'],
            },
        ),
        migrations.AddField(
            model_name='role',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='users.clinic', verbose_name='Клиника'),
        ),
        migrations.AddField(
            model_name='role',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='Системная роль'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='role',
            name='granular_permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='users.permission', verbose_name='Права (новая система)'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('clinic', 'name'), name='unique_role_name_per_clinic'),
        ),
    ]
