# Generated by Django 5.1.4 on 2026-08-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_seed_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='menu_prefs',
            field=models.JSONField(blank=True, default=dict, verbose_name='Настройка меню (личная)'),
        ),
    ]
