# Generated by Django 5.1.4 on 2026-08-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_seed_delete_history_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="use_new_interface",
            field=models.BooleanField(
                default=False, verbose_name="Использует новый интерфейс"
            ),
        ),
    ]
