# Generated by Django 5.1.4 on 2026-08-21 06:07

from django.db import migrations, models


def grandfather_multi_branch_clinics(apps, schema_editor):
    """Клиники, у которых уже больше одного активного филиала, явно уже
    пользовались многофилиальностью — не отбираем эту возможность задним
    числом. Новые/однофилиальные клиники остаются без доступа, пока
    супер-админ не выдаст его явно (см. запрос пользователя)."""
    Clinic = apps.get_model("users", "Clinic")
    Branch = apps.get_model("users", "Branch")
    for clinic in Clinic.objects.all():
        count = Branch.objects.filter(clinic=clinic, is_active=True).count()
        if count > 1:
            clinic.granted_access = ["branches"]
            clinic.save(update_fields=["granted_access"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_user_use_new_interface"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="granted_access",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Доступы (супер-админ)"
            ),
        ),
        migrations.RunPython(grandfather_multi_branch_clinics, noop_reverse),
    ]
