# Generated by Django 5.1.4 on 2026-08-21 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_clinic_granted_access"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicAccessRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clinic_slug",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="Поддомен (если вводили)",
                    ),
                ),
                (
                    "clinic_name",
                    models.CharField(max_length=200, verbose_name="Название клиники"),
                ),
                (
                    "contact_name",
                    models.CharField(max_length=200, verbose_name="Контактное лицо"),
                ),
                ("phone", models.CharField(max_length=30, verbose_name="Телефон")),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("message", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("contacted", "Связались"),
                            ("resolved", "Решено"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Заявка на доступ",
                "verbose_name_plural": "Заявки на доступ",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="clinic",
            name="blocked_features",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Заблокированные функции"
            ),
        ),
        migrations.CreateModel(
            name="BlockedIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(unique=True)),
                ("note", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blocked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Заблокированный IP",
                "verbose_name_plural": "Заблокированные IP",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClinicLoginEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                ("success", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="users.clinic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Вход в систему",
                "verbose_name_plural": "Входы в систему",
                "ordering": ["-created_at"],
            },
        ),
    ]
