# Generated by Django 5.1.4 on 2026-08-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_clinicaccessrequest_clinic_blocked_features_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="blocked_reason",
            field=models.TextField(blank=True, verbose_name="Причина блокировки"),
        ),
    ]
