# Generated by Django 5.1.4 on 2026-08-22 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0030_clinic_blocked_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockedip",
            name="expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Блокировка до"
            ),
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("change", "Изменение"), ("delete", "Удаление")],
                        max_length=10,
                    ),
                ),
                ("action", models.CharField(max_length=40, verbose_name="Действие")),
                ("actor_name", models.CharField(blank=True, max_length=200)),
                ("actor_role", models.CharField(blank=True, max_length=100)),
                ("object_model", models.CharField(blank=True, max_length=60)),
                ("object_id", models.CharField(blank=True, max_length=60)),
                (
                    "object_repr",
                    models.CharField(blank=True, max_length=300, verbose_name="Объект"),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                (
                    "result",
                    models.CharField(
                        choices=[("success", "Успех"), ("fail", "Отказ")],
                        default="success",
                        max_length=10,
                    ),
                ),
                ("diff", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="users.clinic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие аудита",
                "verbose_name_plural": "События аудита",
                "ordering": ["-created_at"],
            },
        ),
    ]
