# Generated by Django 5.1.4 on 2026-08-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0031_blockedip_expires_at_auditevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="category",
            field=models.CharField(
                choices=[
                    ("change", "Изменение"),
                    ("delete", "Удаление"),
                    ("view", "Просмотр"),
                ],
                max_length=10,
            ),
        ),
    ]
