# Generated by Django 5.1.4 on 2026-08-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0032_alter_auditevent_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicloginevent",
            name="attempted_login",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
