# Generated by Django 5.1.4 on 2026-08-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0034_remove_delete_payment_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="archived_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата архивации"
            ),
        ),
        migrations.AddField(
            model_name="clinic",
            name="is_archived",
            field=models.BooleanField(default=False, verbose_name="Архивирована"),
        ),
    ]
