# Generated by Django 5.1.4 on 2026-09-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0035_clinic_archive"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="interface_language",
            field=models.CharField(
                blank=True,
                help_text="Пусто — используется язык клиники по умолчанию",
                max_length=5,
                verbose_name="Язык интерфейса (личный)",
            ),
        ),
    ]
