# Generated by Django 5.1.4 on 2026-10-05 12:09

import apps.tenancy
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_service_price_secondary_alter_service_price"),
        ("users", "0036_user_interface_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salaryscheme",
            name="scheme_type",
            field=models.CharField(
                choices=[
                    ("fixed", "Фиксированная ставка"),
                    ("percent_revenue", "% от выручки"),
                    ("percent_paid", "% от оплат (кассовый)"),
                    ("combined", "Ставка + %"),
                    ("percent_service", "% от услуги (по категориям)"),
                ],
                default="fixed",
                max_length=20,
                verbose_name="Схема",
            ),
        ),
        migrations.CreateModel(
            name="SalaryPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Сумма"
                    ),
                ),
                ("paid_on", models.DateField(verbose_name="Дата выплаты")),
                (
                    "period_from",
                    models.DateField(blank=True, null=True, verbose_name="Период с"),
                ),
                (
                    "period_to",
                    models.DateField(blank=True, null=True, verbose_name="Период по"),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Комментарий"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="users.clinic",
                        verbose_name="Клиника",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_payouts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выплата зарплаты",
                "verbose_name_plural": "Выплаты зарплаты",
                "ordering": ["-paid_on", "-id"],
            },
            bases=(apps.tenancy._ClinicSaveMixin, models.Model),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_clinics", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="SalaryCategoryPercent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Процент (%)",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="services.servicecategory",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_percents",
                        to="users.salaryscheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Процент по категории",
                "verbose_name_plural": "Проценты по категориям",
                "unique_together": {("scheme", "category")},
            },
        ),
    ]
