# Generated by Django 5.1.4 on 2026-10-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0037_salary_percent_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_daily_digest",
            field=models.BooleanField(
                default=True, verbose_name="Telegram: утренняя сводка приёмов"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tg_digest_sent_on",
            field=models.DateField(
                blank=True, null=True, verbose_name="Telegram: сводка отправлена за"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tg_remind_soon",
            field=models.BooleanField(
                default=True, verbose_name="Telegram: напоминать за 30 минут до приёма"
            ),
        ),
    ]
