# Generated by Django 5.1.4 on 2026-07-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=200, verbose_name='Название клиники')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон / WhatsApp')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Город')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contacted', models.BooleanField(default=False, verbose_name='Связались')),
            ],
            options={
                'verbose_name': 'Заявка с лендинга',
                'verbose_name_plural': 'Заявки с лендинга (stom.asia)',
                'ordering': ['-created_at'],
            },
        ),
    ]
