# Generated by Django 5.1.4 on 2026-09-20 14:03

import apps.tenancy
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0036_user_interface_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Закрыта')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.clinic', verbose_name='Клиника')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Беседа с ассистентом',
                'verbose_name_plural': 'Беседы с ассистентом',
                'ordering': ['-updated_at'],
            },
            bases=(apps.tenancy._ClinicSaveMixin, models.Model),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_clinics', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Сотрудник'), ('assistant', 'Ассистент')], max_length=16)),
                ('text', models.TextField(blank=True)),
                ('tool_name', models.CharField(blank=True, max_length=64, verbose_name='Инструмент')),
                ('tool_args', models.JSONField(blank=True, default=dict, verbose_name='Параметры')),
                ('rows_count', models.IntegerField(blank=True, null=True, verbose_name='Строк возвращено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.conversation')),
            ],
            options={
                'verbose_name': 'Реплика',
                'verbose_name_plural': 'Реплики',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', '-updated_at'], name='assistant_c_user_id_6ae267_idx'),
        ),
    ]
