# Generated by Django 5.1.4 on 2026-05-31 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_insurancecompany_historicalpatient_insurance_policy_and_more'),
        ('services', '0002_service_code_service_dms_price_servicematerialnorm'),
        ('treatments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название плана')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Согласован'), ('in_progress', 'В процессе'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='draft', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_plans', to=settings.AUTH_USER_MODEL, verbose_name='Врач')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_plans', to='patients.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'План лечения',
                'verbose_name_plural': 'Планы лечения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_number', models.CharField(blank=True, max_length=20, verbose_name='Зуб(ы)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('scheduled', 'Запланирован'), ('done', 'Выполнен'), ('cancelled', 'Отменён')], default='pending', max_length=20, verbose_name='Статус')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_items', to=settings.AUTH_USER_MODEL, verbose_name='Врач')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='treatments.treatmentplan')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_items', to='services.service', verbose_name='Услуга')),
                ('treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_items', to='treatments.treatment', verbose_name='Выполнен в приёме')),
            ],
            options={
                'verbose_name': 'Пункт плана',
                'verbose_name_plural': 'Пункты плана',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
