# Generated by Django 5.1.4 on 2026-06-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0002_treatmentplan_treatmentplanitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentcure',
            name='tooth_number',
            field=models.CharField(blank=True, max_length=120, verbose_name='Номер зуба'),
        ),
    ]
