# Generated by Django 5.1.4 on 2026-06-02 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0003_alter_treatmentcure_tooth_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentplanitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Скидка %'),
        ),
        migrations.AlterField(
            model_name='treatmentplanitem',
            name='tooth_number',
            field=models.CharField(blank=True, max_length=120, verbose_name='Зуб(ы)'),
        ),
        migrations.CreateModel(
            name='TreatmentPlanStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название этапа')),
                ('duration_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Продолжительность (мин)')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='treatments.treatmentplan')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_stages', to='treatments.treatment', verbose_name='Визит')),
            ],
            options={
                'verbose_name': 'Этап плана',
                'verbose_name_plural': 'Этапы плана',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='treatmentplanitem',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='treatments.treatmentplanstage', verbose_name='Этап'),
        ),
    ]
