# Generated by Django 5.1.4 on 2026-06-02 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_insurancecompany_historicalpatient_insurance_policy_and_more'),
        ('treatments', '0004_treatmentplanitem_discount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecordTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('complaints', models.TextField(blank=True, verbose_name='Жалобы')),
                ('anamnesis', models.TextField(blank=True, verbose_name='Анамнез')),
                ('external_exam', models.TextField(blank=True, verbose_name='Внешний осмотр')),
                ('objective', models.TextField(blank=True, verbose_name='Объективно')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Диагноз')),
                ('treatment', models.TextField(blank=True, verbose_name='Лечение')),
                ('recommendations', models.TextField(blank=True, verbose_name='Рекомендации')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Шаблон ЭМК',
                'verbose_name_plural': 'Шаблоны ЭМК',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaints', models.TextField(blank=True, verbose_name='Жалобы')),
                ('anamnesis', models.TextField(blank=True, verbose_name='Анамнез')),
                ('external_exam', models.TextField(blank=True, verbose_name='Внешний осмотр')),
                ('objective', models.TextField(blank=True, verbose_name='Объективно')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Диагноз')),
                ('treatment_text', models.TextField(blank=True, verbose_name='Лечение')),
                ('recommendations', models.TextField(blank=True, verbose_name='Рекомендации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patient', verbose_name='Пациент')),
                ('treatment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emr', to='treatments.treatment', verbose_name='Приём')),
            ],
            options={
                'verbose_name': 'Медкарта (ЭМК)',
                'verbose_name_plural': 'Медкарты (ЭМК)',
            },
        ),
    ]
