# Generated by Django 5.1.4 on 2026-06-02 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_insurancecompany_historicalpatient_insurance_policy_and_more'),
        ('treatments', '0005_medicalrecordtemplate_medicalrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToothStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=40, verbose_name='Код')),
                ('name', models.CharField(max_length=80, verbose_name='Название')),
                ('color', models.CharField(default='#6366F1', max_length=9, verbose_name='Цвет')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Статус зуба',
                'verbose_name_plural': 'Статусы зубов',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ToothCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_number', models.PositiveSmallIntegerField(verbose_name='Зуб (FDI)')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Заметка')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tooth_conditions', to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conditions', to='treatments.toothstatus')),
            ],
            options={
                'verbose_name': 'Состояние зуба',
                'verbose_name_plural': 'Состояния зубов',
                'ordering': ['tooth_number'],
                'unique_together': {('patient', 'tooth_number')},
            },
        ),
    ]
