# Generated by Django 5.1.4 on 2026-06-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0008_alter_medicalrecordtemplate_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentfile',
            name='kind',
            field=models.CharField(choices=[('xray', 'Рентген'), ('before', 'Фото «до»'), ('after', 'Фото «после»'), ('document', 'Документ'), ('other', 'Другое')], default='xray', max_length=20, verbose_name='Тип'),
        ),
    ]
