# Generated by Django 5.1.4 on 2026-06-05 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointment_updated_at'),
        ('treatments', '0009_treatmentfile_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltreatment',
            name='appointment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appointments.appointment', verbose_name='Запись'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', to='appointments.appointment', verbose_name='Запись'),
        ),
    ]
