# Generated by Django 5.1.4 on 2026-06-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0010_historicaltreatment_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='exam_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные осмотра'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='icd_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Код МКБ-10'),
        ),
    ]
