# Generated by Django 5.1.4 on 2026-06-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0011_medicalrecord_exam_data_medicalrecord_icd_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentfile',
            name='tooth_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Зуб (FDI)'),
        ),
    ]
