# Generated by Django 5.1.4 on 2026-06-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0012_treatmentfile_tooth_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentfile',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий врача'),
        ),
        migrations.AlterField(
            model_name='treatmentfile',
            name='kind',
            field=models.CharField(choices=[('intraoral', 'Прицельный снимок'), ('opg', 'ОПТГ (панорамный)'), ('cbct', 'КЛКТ (3D)'), ('photo_oral', 'Фото полости рта'), ('photo_face', 'Фото лица'), ('before', 'Фото «до»'), ('after', 'Фото «после»'), ('xray', 'Рентген'), ('document', 'Документ'), ('other', 'Другое')], default='intraoral', max_length=20, verbose_name='Тип'),
        ),
    ]
