# Generated by Django 5.1.4 on 2026-06-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0013_treatmentfile_comment_alter_treatmentfile_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltreatment',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('planned', 'Запланирован'), ('in_progress', 'В процессе'), ('completed', 'Завершён'), ('cancelled', 'Отменён'), ('paid', 'Оплачен')], default='planned', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('planned', 'Запланирован'), ('in_progress', 'В процессе'), ('completed', 'Завершён'), ('cancelled', 'Отменён'), ('paid', 'Оплачен')], default='planned', max_length=20, verbose_name='Статус'),
        ),
    ]
