# Generated by Django 5.1.4 on 2026-06-21 15:39

import uuid
from django.db import migrations, models


def gen_tokens(apps, schema_editor):
    Treatment = apps.get_model("treatments", "Treatment")
    for pk in Treatment.objects.values_list("pk", flat=True):
        Treatment.objects.filter(pk=pk).update(public_token=uuid.uuid4())


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0014_alter_historicaltreatment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltreatment',
            name='public_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='treatment',
            name='public_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(gen_tokens, migrations.RunPython.noop),
    ]
