# Generated by Django 5.1.4 on 2026-06-22 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0003_alter_techniciantask_options_and_more'),
        ('treatments', '0015_historicaltreatment_public_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentcure',
            name='lab_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='technicians.techniciantask', verbose_name='Заказ технику'),
        ),
        migrations.AddField(
            model_name='treatmentcure',
            name='warranty_until',
            field=models.DateField(blank=True, null=True, verbose_name='Гарантия до'),
        ),
    ]
