# Generated by Django 5.1.4 on 2026-07-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0016_treatmentcure_lab_order_treatmentcure_warranty_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltreatment',
            name='number',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='№ приёма'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='number',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='№ приёма'),
        ),
    ]
