# Generated by Django 5.1.4 on 2026-08-09 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_lead'),
        ('treatments', '0018_backfill_treatment_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToothGumStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=40, verbose_name='Код')),
                ('name', models.CharField(max_length=80, verbose_name='Название')),
                ('color', models.CharField(default='#6366F1', max_length=9, verbose_name='Цвет')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Статус дёсен',
                'verbose_name_plural': 'Статусы дёсен',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ToothSurfaceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=40, verbose_name='Код')),
                ('name', models.CharField(max_length=80, verbose_name='Название')),
                ('color', models.CharField(default='#6366F1', max_length=9, verbose_name='Цвет')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Статус поверхности зуба',
                'verbose_name_plural': 'Статусы поверхностей зубов',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ToothGumCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_number', models.PositiveSmallIntegerField(verbose_name='Зуб (FDI)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tooth_gum_conditions', to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conditions', to='treatments.toothgumstatus')),
            ],
            options={
                'verbose_name': 'Состояние дёсен зуба',
                'verbose_name_plural': 'Состояния дёсен зубов',
                'ordering': ['tooth_number'],
                'unique_together': {('patient', 'tooth_number')},
            },
        ),
        migrations.CreateModel(
            name='ToothSurfaceCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_number', models.PositiveSmallIntegerField(verbose_name='Зуб (FDI)')),
                ('surface_index', models.PositiveSmallIntegerField(verbose_name='Поверхность (0–5)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tooth_surface_conditions', to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conditions', to='treatments.toothsurfacestatus')),
            ],
            options={
                'verbose_name': 'Состояние поверхности зуба',
                'verbose_name_plural': 'Состояния поверхностей зубов',
                'ordering': ['tooth_number', 'surface_index'],
                'unique_together': {('patient', 'tooth_number', 'surface_index')},
            },
        ),
    ]
