# Generated by Django 5.1.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0019_toothgumstatus_toothsurfacestatus_toothgumcondition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltreatment',
            name='needs_doctor_confirmation',
            field=models.BooleanField(
                default=False,
                help_text='Создано кассиром через «Быструю продажу» — врач ещё не подтвердил, что услуга была оказана.',
                verbose_name='Требует подтверждения врача',
            ),
        ),
        migrations.AddField(
            model_name='treatment',
            name='needs_doctor_confirmation',
            field=models.BooleanField(
                default=False,
                help_text='Создано кассиром через «Быструю продажу» — врач ещё не подтвердил, что услуга была оказана.',
                verbose_name='Требует подтверждения врача',
            ),
        ),
    ]
