# Generated by Django 5.1.4 on 2026-08-15 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0016_lead"),
        ("treatments", "0021_treatmentcure_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatmentfile",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="patients.patient",
                verbose_name="Пациент",
            ),
        ),
        migrations.AlterField(
            model_name="treatmentfile",
            name="treatment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="treatments.treatment",
            ),
        ),
    ]
