# Generated by Django 5.1.4 on 2026-08-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treatments", "0022_treatmentfile_patient_alter_treatmentfile_treatment"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltreatment",
            name="history_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
