# Generated by Django 5.1.4 on 2026-07-15 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0016_clinic_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(max_length=100, verbose_name='Модель')),
                ('object_pk', models.CharField(max_length=64, verbose_name='ID записи')),
                ('object_repr', models.CharField(blank=True, max_length=300, verbose_name='Описание записи')),
                ('local_data', models.JSONField(verbose_name='Локальная версия (офлайн)')),
                ('cloud_data', models.JSONField(blank=True, null=True, verbose_name='Облачная версия (на момент конфликта)')),
                ('local_updated_at', models.DateTimeField(blank=True, null=True)),
                ('cloud_updated_at', models.DateTimeField(blank=True, null=True)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('resolution', models.CharField(blank=True, choices=[('cloud', 'Оставили облачную версию'), ('local', 'Применили локальную версию')], max_length=10)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_conflicts', to='users.clinic', verbose_name='Клиника')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Конфликт синхронизации',
                'verbose_name_plural': 'Конфликты синхронизации',
                'ordering': ['-created_at'],
            },
        ),
    ]
