# Generated by Django 5.1.4 on 2026-05-31 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Страховая компания')),
                ('short_name', models.CharField(blank=True, max_length=100, verbose_name='Краткое наименование')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Контактное лицо')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Адрес')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Страховая компания',
                'verbose_name_plural': 'Страховые компании',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='insurance_policy',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер полиса ДМС'),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='insurance_valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Полис действует до'),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='primary_doctor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Лечащий врач'),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_policy',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер полиса ДМС'),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Полис действует до'),
        ),
        migrations.AddField(
            model_name='patient',
            name='primary_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_patients', to=settings.AUTH_USER_MODEL, verbose_name='Лечащий врач'),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='insurance',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patients.insurancecompany', verbose_name='Страховая компания'),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='patients.insurancecompany', verbose_name='Страховая компания'),
        ),
    ]
