# Generated by Django 5.1.4 on 2026-06-03 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_options_alter_patient_managers_and_more'),
        ('users', '0004_clinic_alter_branch_managers_branch_clinic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='clinic',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.clinic', verbose_name='Клиника'),
        ),
        migrations.AddField(
            model_name='patient',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.clinic', verbose_name='Клиника'),
        ),
    ]
