# Generated by Django 5.1.4 on 2026-06-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_historicalpatient_clinic_patient_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='last_debt_reminder',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее напоминание о долге'),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_debt_reminder',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее напоминание о долге'),
        ),
    ]
