# Generated by Django 5.1.4 on 2026-06-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_historicalpatient_last_debt_reminder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='number',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='№ пациента'),
        ),
        migrations.AddField(
            model_name='patient',
            name='number',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='№ пациента'),
        ),
    ]
