# Generated by Django 5.1.4 on 2026-06-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_backfill_patient_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='allergy',
            field=models.TextField(blank=True, null=True, verbose_name='Аллергии'),
        ),
        migrations.AddField(
            model_name='patient',
            name='allergy',
            field=models.TextField(blank=True, null=True, verbose_name='Аллергии'),
        ),
    ]
