# Generated by Django 5.1.4 on 2026-06-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_historicalpatient_allergy_patient_allergy'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10, verbose_name='Группа крови'),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10, verbose_name='Группа крови'),
        ),
    ]
