# Generated by Django 5.1.4 on 2026-06-18 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_historicalpatient_blood_group_patient_blood_group'),
        ('users', '0016_clinic_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('phone_norm', models.CharField(db_index=True, default='', editable=False, max_length=15)),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='ФИО (если известно)')),
                ('reason', models.TextField(verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.clinic', verbose_name='Добавила клиника')),
            ],
            options={
                'verbose_name': 'Чёрный список',
                'verbose_name_plural': 'Чёрный список',
                'ordering': ['-created_at'],
            },
        ),
    ]
