# Generated by Django 5.1.4 on 2026-06-20 14:04

import apps.tenancy
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_appointment_overdue_notified'),
        ('patients', '0010_blacklistentry'),
        ('users', '0016_clinic_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(verbose_name='Дата и время посещения')),
                ('purpose', models.CharField(blank=True, max_length=300, verbose_name='Повод / услуга')),
                ('note', models.TextField(blank=True, verbose_name='Заметка')),
                ('source', models.CharField(choices=[('auto', 'Автоматически (запись)'), ('manual', 'Вручную')], default='manual', max_length=10, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='appointments.appointment', verbose_name='Связанная запись')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.clinic', verbose_name='Клиника')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Врач')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещения',
                'ordering': ['-visited_at'],
            },
            bases=(apps.tenancy._ClinicSaveMixin, models.Model),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_clinics', django.db.models.manager.Manager()),
            ],
        ),
    ]
