# Generated by Django 5.1.4 on 2026-07-12 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_patientvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='phone_norm',
            field=models.CharField(db_index=True, default='', editable=False, max_length=15),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='pin',
            field=models.CharField(blank=True, db_index=True, help_text='Персональный идентификационный номер (Кыргызстан), 14 цифр', max_length=14, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'ИИН должен содержать ровно 14 цифр')], verbose_name='ИИН'),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_norm',
            field=models.CharField(db_index=True, default='', editable=False, max_length=15),
        ),
        migrations.AddField(
            model_name='patient',
            name='pin',
            field=models.CharField(blank=True, db_index=True, help_text='Персональный идентификационный номер (Кыргызстан), 14 цифр', max_length=14, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'ИИН должен содержать ровно 14 цифр')], verbose_name='ИИН'),
        ),
    ]
