# Generated by Django 5.1.4 on 2026-07-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_sharedphonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Заполняется автоматически, когда пациент нажимает Start у бота клиники и делится номером', null=True, verbose_name='Telegram chat_id'),
        ),
        migrations.AddField(
            model_name='patient',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Заполняется автоматически, когда пациент нажимает Start у бота клиники и делится номером', null=True, verbose_name='Telegram chat_id'),
        ),
    ]
