# Generated by Django 5.1.4 on 2026-08-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0016_lead"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpatient",
            name="history_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
