# Generated by Django 5.1.4 on 2026-09-21 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0017_historicalpatient_history_ip"),
        ("users", "0036_user_interface_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpatient",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="users.branch",
                verbose_name="Филиал регистрации",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="patients",
                to="users.branch",
                verbose_name="Филиал регистрации",
            ),
        ),
    ]
