# Generated by Django 5.1.4 on 2026-05-29 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Кабинет')),
                ('color', models.CharField(default='#10B981', max_length=7, verbose_name='Цвет')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
                'ordering': ['branch', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='Начало')),
                ('end_at', models.DateTimeField(verbose_name='Конец')),
                ('status', models.CharField(choices=[('scheduled', 'Записан'), ('confirmed', 'Подтверждён'), ('arrived', 'Пришёл'), ('in_progress', 'Принимается'), ('completed', 'Завершён'), ('no_show', 'Не пришёл'), ('cancelled', 'Отменён')], default='scheduled', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('source', models.CharField(choices=[('manual', 'Вручную'), ('online', 'Онлайн'), ('telegram', 'Telegram')], default='manual', max_length=20, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='users.branch', verbose_name='Филиал')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['start_at'],
            },
        ),
    ]
