# Generated by Django 5.1.4 on 2026-06-02 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Причина отмены')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Причина отмены',
                'verbose_name_plural': 'Причины отмены',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancel_note',
            field=models.CharField(blank=True, max_length=300, verbose_name='Комментарий к отмене'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='appointments.cancellationreason', verbose_name='Причина отмены'),
        ),
    ]
