# Generated by Django 5.1.4 on 2026-06-02 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_cancellationreason_appointment_cancel_note_and_more'),
        ('services', '0002_service_code_service_dms_price_servicematerialnorm'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='appointments_multi', to='services.service', verbose_name='Услуги'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='services.service', verbose_name='Услуга (основная)'),
        ),
    ]
