# Generated by Django 5.1.4 on 2026-06-03 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointment_options_alter_appointment_managers_and_more'),
        ('users', '0004_clinic_alter_branch_managers_branch_clinic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.clinic', verbose_name='Клиника'),
        ),
    ]
