# Generated by Django 5.1.4 on 2026-06-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reminded_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminded_hour',
            field=models.BooleanField(default=False),
        ),
    ]
