# Generated by Django 5.1.4 on 2026-06-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_appointment_reminded_day_appointment_reminded_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='gcal_event_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='ID события Google Calendar'),
        ),
    ]
