# Generated by Django 5.1.4 on 2026-06-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_appointment_gcal_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='overdue_notified',
            field=models.BooleanField(default=False),
        ),
    ]
