# Generated by Django 5.1.4 on 2026-10-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0010_appointment_overdue_notified"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="doctor_reminded_for",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
