# Generated by Django 5.1.4 on 2026-10-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0011_appointment_doctor_reminded_for"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Вручную"),
                    ("online", "Онлайн"),
                    ("telegram", "Telegram"),
                    ("whatsapp", "WhatsApp"),
                    ("ai", "ИИ-ассистент"),
                ],
                default="manual",
                max_length=20,
                verbose_name="Источник",
            ),
        ),
    ]
