# Generated by Django 5.1.4 on 2026-06-05 04:08

import django.db.models.deletion
from django.db import migrations, models


def backfill_clinic(apps, schema_editor):
    """Существующим уведомлениям проставить клинику получателя."""
    Notification = apps.get_model('notifications', 'Notification')
    for n in Notification.objects.filter(clinic__isnull=True).select_related('user'):
        cid = getattr(n.user, 'clinic_id', None)
        if cid:
            Notification.objects.filter(pk=n.pk).update(clinic_id=cid)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_pushsubscription'),
        ('users', '0008_user_can_view_all_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.clinic', verbose_name='Клиника'),
        ),
        migrations.RunPython(backfill_clinic, noop),
    ]
