# Generated by Django 5.1.4 on 2026-06-07 18:16

import apps.tenancy
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_actor'),
        ('patients', '0004_historicalpatient_clinic_patient_clinic'),
        ('users', '0013_branch_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('kind', models.CharField(choices=[('manual', 'Произвольное'), ('appointment', 'О записи'), ('reminder', 'Напоминание о приёме'), ('confirm', 'Подтверждение записи'), ('debt', 'О задолженности'), ('birthday', 'Поздравление')], default='manual', max_length=20, verbose_name='Тип')),
                ('body', models.TextField(verbose_name='Текст сообщения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.clinic', verbose_name='Клиника')),
            ],
            options={
                'verbose_name': 'Шаблон сообщения',
                'verbose_name_plural': 'Шаблоны сообщений',
                'ordering': ['kind', 'name'],
            },
            bases=(apps.tenancy._ClinicSaveMixin, models.Model),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_clinics', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WaMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('out', 'Исходящее'), ('in', 'Входящее')], default='out', max_length=3)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('body', models.TextField()),
                ('ok', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.clinic', verbose_name='Клиника')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wa_messages', to='patients.patient', verbose_name='Пациент')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WhatsApp-сообщение',
                'verbose_name_plural': 'WhatsApp-сообщения',
                'ordering': ['created_at'],
            },
            bases=(apps.tenancy._ClinicSaveMixin, models.Model),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_clinics', django.db.models.manager.Manager()),
            ],
        ),
    ]
