# Generated by Django 5.1.4 on 2026-06-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_messagetemplate_wamessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='wamessage',
            name='read',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
