# Generated by Django 5.1.4 on 2026-06-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_wamessage_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='kind',
            field=models.CharField(choices=[('manual', 'Произвольное'), ('appointment', 'О записи'), ('reminder', 'Напоминание о приёме (за день)'), ('reminder_hour', 'Напоминание (за час)'), ('confirm', 'Подтверждение записи'), ('debt', 'О задолженности'), ('birthday', 'Поздравление')], default='manual', max_length=20, verbose_name='Тип'),
        ),
    ]
