# Generated by Django 5.1.4 on 2026-06-11 16:00

import apps.tenancy
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_messagetemplate_kind'),
        ('users', '0013_branch_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=64, verbose_name='ID группы (@g.us)')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Название группы')),
                ('notify', models.BooleanField(default=True, verbose_name='Слать уведомления')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.clinic', verbose_name='Клиника')),
            ],
            options={
                'verbose_name': 'WhatsApp-группа',
                'verbose_name_plural': 'WhatsApp-группы',
                'ordering': ['name', 'chat_id'],
                'unique_together': {('clinic', 'chat_id')},
            },
            bases=(apps.tenancy._ClinicSaveMixin, models.Model),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_clinics', django.db.models.manager.Manager()),
            ],
        ),
    ]
