# Generated by Django 5.1.4 on 2026-06-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_wagroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('appointment', 'Запись'), ('task', 'Задача'), ('payment', 'Платёж'), ('wa', 'WhatsApp'), ('system', 'Система'), ('reminder', 'Напоминание')], max_length=20, verbose_name='Тип'),
        ),
    ]
