# Generated by Django 5.1.4 on 2026-07-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='wamessage',
            name='channel',
            field=models.CharField(choices=[('wa', 'WhatsApp'), ('tg', 'Telegram')], db_index=True, default='wa', max_length=3, verbose_name='Канал'),
        ),
    ]
