# Generated by Django 5.1.4 on 2026-07-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_wamessage_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='wamessage',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='chat_media/%Y/%m/', verbose_name='Медиафайл'),
        ),
        migrations.AddField(
            model_name='wamessage',
            name='media_type',
            field=models.CharField(blank=True, choices=[('voice', 'Голосовое'), ('audio', 'Аудио'), ('image', 'Фото'), ('video', 'Видео'), ('document', 'Документ')], max_length=10, verbose_name='Тип медиа'),
        ),
        migrations.AlterField(
            model_name='wamessage',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
