# Generated by Django 5.1.4 on 2026-09-22 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0011_wamessage_media_file_wamessage_media_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("appointment", "Запись"),
                    ("task", "Задача"),
                    ("payment", "Платёж"),
                    ("wa", "WhatsApp"),
                    ("system", "Система"),
                    ("reminder", "Напоминание"),
                    ("broadcast", "Объявление супер-админа"),
                ],
                max_length=20,
                verbose_name="Тип",
            ),
        ),
    ]
