# Generated by Django 5.1.4 on 2026-09-22 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0012_alter_notification_type"),
        ("users", "0036_user_interface_language"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Broadcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=300, verbose_name="Текст")),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("all", "Всем сотрудникам"),
                            ("directors", "Директорам"),
                            ("doctors", "Врачам"),
                        ],
                        default="all",
                        max_length=20,
                        verbose_name="Кому",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "clinics",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="users.clinic",
                        verbose_name="Клиники",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Отправитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="broadcast",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="notifications.broadcast",
                verbose_name="Рассылка",
            ),
        ),
    ]
