# Generated by Django 5.1.4 on 2026-09-24 03:49

import apps.tenancy
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0013_broadcast_notification_broadcast"),
        ("users", "0036_user_interface_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="TgGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.BigIntegerField(verbose_name="ID чата Telegram")),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Название группы"
                    ),
                ),
                (
                    "notify",
                    models.BooleanField(default=True, verbose_name="Слать уведомления"),
                ),
                (
                    "last_summary_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="Последняя сводка"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="users.clinic",
                        verbose_name="Клиника",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram-группа",
                "verbose_name_plural": "Telegram-группы",
                "ordering": ["title", "chat_id"],
                "unique_together": {("clinic", "chat_id")},
            },
            bases=(apps.tenancy._ClinicSaveMixin, models.Model),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_clinics", django.db.models.manager.Manager()),
            ],
        ),
    ]
