# Generated by Django 5.1.4 on 2026-09-24 15:31

import apps.tenancy
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0014_tggroup"),
        ("users", "0036_user_interface_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="TgChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.BigIntegerField(verbose_name="ID чата Telegram")),
                (
                    "lang",
                    models.CharField(blank=True, max_length=2, verbose_name="Язык"),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Шаг диалога"
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="users.clinic",
                        verbose_name="Клиника",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram-чат пациента",
                "verbose_name_plural": "Telegram-чаты пациентов",
                "unique_together": {("clinic", "chat_id")},
            },
            bases=(apps.tenancy._ClinicSaveMixin, models.Model),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_clinics", django.db.models.manager.Manager()),
            ],
        ),
    ]
