# Generated by Django 5.1.4 on 2026-10-06 04:37

import apps.tenancy
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0016_assistant_chats"),
        ("users", "0038_user_tg_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="wamessage",
            name="ai_status",
            field=models.CharField(blank=True, db_index=True, default="", max_length=8),
        ),
        migrations.AddField(
            model_name="wamessage",
            name="by_ai",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="wamessage",
            name="transcript",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="ChatBotState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel", models.CharField(max_length=3)),
                ("address", models.CharField(max_length=40)),
                ("paused", models.BooleanField(default=False)),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="users.clinic",
                        verbose_name="Клиника",
                    ),
                ),
            ],
            options={
                "unique_together": {("clinic", "channel", "address")},
            },
            bases=(apps.tenancy._ClinicSaveMixin, models.Model),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_clinics", django.db.models.manager.Manager()),
            ],
        ),
    ]
